[tool.poetry]
name = "detection_rules"
version = "0.1.0"
description = "Detection Rules is the home for rules used by Elastic Security. This repository is used for the development, maintenance, testing, validation, and release of rules for Elastic Security’s Detection Engine."
readme = "README.md"
license = "LICENSE.txt"
authors = ["Elastic"]
keywords = ["Detection Rules", "Continuous Monitoring", "Data Protection", "Elastic", "Elastic Endgame", "Endpoint Security"]
classifiers = [
  "Topic :: Software Development :: Build Tools",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python",
  "Topic :: Security",
  "Topic :: Software Development :: Libraries :: Python Modules",
  "Topic :: Software Development :: Libraries",
  "Topic :: Software Development :: Testing",
  "Topic :: Software Development",
  "Topic :: Utilities"
]

[tool.poetry.dependencies]
python = "^3.8"
python-dotenv = "^1.0.0"
pytoml = "^0.1.21"
eql = "^0.9.17"
semver = "^3.0.1"
marko = "^2.0.0"
marshmallow-dataclass = "^8.5.14"
typeguard = "^4.1.0"
marshmallow-jsonschema = "^0.13.0"
marshmallow-union = "^0.1.15.post1"
jsl = "^0.2.4"
toml = "^0.10.2"
xlsxwriter = "^3.1.2"

[tool.poetry.group.dev.dependencies]
openai = "^0.27.8"

[project.urls]
"Homepage" = "https://github.com/elastic/detection-rules"
"Bug Reports" = "https://github.com/elastic/detection-rules/issues"
"Research" = "https://www.elastic.co/security-labs"
"Elastic" = "https://www.elastic.co"

[tool.setuptools]
package-data = {"kql" = ["*.g"]}
packages = ["detection_rules",	"kql",	"kibana",	"rta"]

[tool.pytest.ini_options]
filterwarnings = [
	"ignore::DeprecationWarning"
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
