[metadata]
creation_date = "2023/04/26"
integration = ["endpoint"]
maturity = "production"
min_stack_comments = "New fields added: required_fields, related_integrations, setup"
min_stack_version = "8.3.0"
updated_date = "2023/06/23"

[rule]
author = ["Elastic"]
description = """
Identifies the execution of the mimipenguin exploit script which is linux adaptation of Windows tool mimikatz.
Mimipenguin exploit script is used to dump clear text passwords from a currently logged-in user. The tool exploits
a known vulnerability CVE-2018-20781. Malicious actors can exploit the cleartext credentials in memory by
dumping the process and extracting lines that have a high probability of containing cleartext passwords.
"""
from = "now-9m"
index = ["logs-endpoint.events.*"]
language = "eql"
license = "Elastic License v2"
name = "Potential Linux Credential Dumping via Proc Filesystem"
references = [
    "https://github.com/huntergregal/mimipenguin",
    "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2018-20781"
]
note = """## Triage and analysis

### Investigating Credential Dumping via Proc Filesystem

The rule identifies execution of the mimipenguin exploit script password-cracking tool which is linux adaptation of
Windows tool mimikatz. Mimipenguin exploit script is used to dump clear text passwords from a currently logged-in user.

#### Possible investigation steps

- Identify the session entry leader and session user.
- Examine the contents of session leading to the mimipenguin exploit script execution via the Session View.
- Examine the command execution pattern in the session, which may lead to suspicious activities.
- Examine the command execution post mimipenguin exploit to indicate any exfiltration of clear text passwords.
- Investigate other alerts associated with the user/host during the past 48 hours.

### False positive analysis

- The exploit tool execution can only be a check to assert or test security measures by authorised system administrators.
- As such the exploit tool should not be executed by users on the host machine.

### Response and remediation

- Initiate the incident response process based on the outcome of the triage.
- Ensure active session(s) on the host(s) are terminated as the malicious user can exploit the cleartext credentials in memory.
- Isolate the involved host(s) to prevent further post-compromise behavior.
- If the analysis has shown exfiltration of cleartext credentials, analyse the impact of data that has been exfiltrated.
- Perform a comprehensive examination of the compromised credentials that might have been used for unauthorized access or data exfiltration, and temporarily prevent their usage until a thorough analysis is conducted. Additionally, change those passwords before allowing any further usage.
- Determine the initial vector abused by the attacker and take action to prevent reinfection through the same vector.
- Using the incident response data, update logging and audit policies to improve the mean time to detect (MTTD) and the mean time to respond (MTTR).
"""
risk_score = 47
rule_id = "ef100a2e-ecd4-4f72-9d1e-2f779ff3c311"
severity = "medium"
tags = ["Domain: Endpoint", "OS: Linux", "Use Case: Threat Detection", "Tactic: Credential Access", "Use Case: Vulnerability"]
type = "eql"
query = '''
sequence by process.parent.name,host.name with maxspan=1m
[process where host.os.type == "linux" and process.name == "ps" and event.action == "exec"
 and process.args in ("-eo", "pid", "command") ]

[process where host.os.type == "linux" and process.name == "strings" and event.action == "exec"
 and process.args : "/tmp/*" ]
'''


[[rule.threat]]
framework = "MITRE ATT&CK"
[[rule.threat.technique]]
id = "T1003"
name = "OS Credential Dumping"
reference = "https://attack.mitre.org/techniques/T1003/"
[[rule.threat.technique.subtechnique]]
id = "T1003.007"
name = "Proc Filesystem"
reference = "https://attack.mitre.org/techniques/T1003/007/"

[[rule.threat.technique]]
id = "T1212"
name = "Exploitation for Credential Access"
reference = "https://attack.mitre.org/techniques/T1212/"



[rule.threat.tactic]
id = "TA0006"
name = "Credential Access"
reference = "https://attack.mitre.org/tactics/TA0006/"

