[metadata]
creation_date = "2020/04/27"
integration = ["endpoint"]
maturity = "production"
min_stack_comments = "New fields added: required_fields, related_integrations, setup"
min_stack_version = "8.3.0"
updated_date = "2023/07/17"

[rule]
author = ["Elastic"]
description = """
Adversaries may attempt to disable the syslog service in an attempt to an attempt to disrupt event logging and evade
detection by security controls.
"""
from = "now-9m"
index = ["auditbeat-*", "logs-endpoint.events.*", "endgame-*"]
language = "eql"
license = "Elastic License v2"
name = "Attempt to Disable Syslog Service"
note = """## Triage and analysis

### Investigating Attempt to Disable Syslog Service

Syslog is the general standard for logging system and program messages in the Linux environment.
This service constitutes the system log service daemon, where any program can utilize its functionality for logging,
debugging, security, normal operation activities, and Linux kernel messages. This rule identifies the
execution of commands to disable the syslog service. Attackers may attempt to disrupt event logging to evade security
controls for processes that use this service daemon for logs.

#### Possible investigation steps

- Identify the session entry leader and session user.
- Use [Session View](https://www.elastic.co/guide/en/security/master/session-view.html) to examine the session and locate commands that turned off the syslog service.
- Examine the command execution pattern within the session for suspicious activities.
- Examine processes and services that ran after the syslog service was turned off. They could be malicious activity.
- Investigate any other alerts or malicious activities associated with the user/host during the past 48 hours.

### False positive analysis

- Infrastructure deployment or operation scripts trying to stop syslog services.

### Response and remediation

- Initiate the incident response process based on the outcome of the triage.
- Isolate the affected host to prevent further post-compromise behavior.
- Check process and services that could have been started after the syslog service was turned off, and terminate suspicious network processes.
- Terminate active sessions on the hosts to prevent attackers from regaining control.
- Determine the initial vector abused by the attacker and take action to prevent reinfection through the same vector.
- Using the incident response data, update logging and audit policies to improve the mean time to detect (MTTD) and the mean time to respond (MTTR).
"""
risk_score = 47
rule_id = "2f8a1226-5720-437d-9c20-e0029deb6194"
severity = "medium"
tags = ["Domain: Endpoint", "OS: Linux", "Use Case: Threat Detection", "Tactic: Defense Evasion", "Data Source: Elastic Endgame", "Resources: Investigation Guide"]
timestamp_override = "event.ingested"
type = "eql"

query = '''
process where host.os.type == "linux" and event.action in ("exec", "exec_event") and
 ( (process.name == "service" and process.args == "stop") or
   (process.name == "chkconfig" and process.args == "off") or
   (process.name == "systemctl" and process.args in ("disable", "stop", "kill"))
 ) and process.args in ("syslog", "rsyslog", "syslog-ng")
'''


[[rule.threat]]
framework = "MITRE ATT&CK"
[[rule.threat.technique]]
id = "T1562"
name = "Impair Defenses"
reference = "https://attack.mitre.org/techniques/T1562/"
[[rule.threat.technique.subtechnique]]
id = "T1562.001"
name = "Disable or Modify Tools"
reference = "https://attack.mitre.org/techniques/T1562/001/"



[rule.threat.tactic]
id = "TA0005"
name = "Defense Evasion"
reference = "https://attack.mitre.org/tactics/TA0005/"

