[metadata]
creation_date = "2023/02/22"
integration = ["endpoint"]
maturity = "production"
min_stack_comments = "New fields added: required_fields, related_integrations, setup"
min_stack_version = "8.3.0"
updated_date = "2023/07/17"

[rule]
author = ["Elastic"]
description = """
Adversaries may attempt to disable the iptables or firewall service in an attempt to affect how a host is allowed to
receive or send network traffic.
"""
from = "now-9m"
index = ["logs-endpoint.events.*"]
language = "eql"
license = "Elastic License v2"
name = "Attempt to Disable IPTables or Firewall"
note = """## Triage and analysis

### Investigating Attempt to Disable IPTables or Firewall

Iptables is a Linux firewall program that uses tables to filter incoming and outgoing network traffic.
Tables contain chains, which are sets of rules that monitor data packets.
This rule identifies efforts to turn off iptables or firewalld to prevent hosts from receiving or sending network traffic.

#### Possible investigation steps

- Identify the session entry leader and session user.
- Use [Session View](https://www.elastic.co/guide/en/security/master/session-view.html) to examine the session and locate commands that turned off iptables or firewalld.
- Examine the command execution pattern within the session for suspicious activities.
- Examine processes and services that ran after iptables or firewalld were turned off. They could be malicious activity.
- Investigate other alerts associated with the user/host during the past 48 hours.

### False positive analysis

- Infrastructure deployment or operation scripts trying to stop iptables or firewalld services.

### Response and remediation

- Initiate the incident response process based on the outcome of the triage.
- Terminate active sessions on the hosts to prevent attackers from manipulating network traffic flow.
- Isolate the affected host to prevent further post-compromise behavior.
- Check process and services that could have been started after iptables or firewalld were turned off, and terminate suspicious network processes ran by the suspicious user.
- Determine the initial vector abused by the attacker and take action to prevent reinfection through the same vector.
- Using the incident response data, update logging and audit policies to improve the mean time to detect (MTTD) and the mean time to respond (MTTR).
"""
risk_score = 21
rule_id = "83e9c2b3-24ef-4c1d-a8cd-5ebafb5dfa2f"
severity = "low"
tags = ["Domain: Endpoint", "OS: Linux", "Use Case: Threat Detection", "Tactic: Defense Evasion", "Resources: Investigation Guide"]
timestamp_override = "event.ingested"
type = "eql"
query = '''
process where host.os.type == "linux" and event.type == "start" and event.action == "exec" and
 (
   /* disable FW */
   (
     (process.name == "ufw" and process.args == "disable") or
     (process.name == "iptables" and process.args == "-F" and process.args_count == 2)
   ) or

   /* stop FW service */
   (
     ((process.name == "service" and process.args == "stop") or
       (process.name == "chkconfig" and process.args == "off") or
       (process.name == "systemctl" and process.args in ("disable", "stop", "kill"))) and
    process.args in ("firewalld", "ip6tables", "iptables")
    )
  )
'''


[[rule.threat]]
framework = "MITRE ATT&CK"
[[rule.threat.technique]]
name = "Impair Defenses"
id = "T1562"
reference = "https://attack.mitre.org/techniques/T1562/"
[[rule.threat.technique.subtechnique]]
name = "Disable or Modify Tools"
id = "T1562.001"
reference = "https://attack.mitre.org/techniques/T1562/001/"



[rule.threat.tactic]
name = "Defense Evasion"
id = "TA0005"
reference = "https://attack.mitre.org/tactics/TA0005/"

